# hostname (and path) to the root
baseURL: "https://vanillajsguides.com"

# Customer parameters
params:
  description: "Short, focused vanilla JS ebooks and video courses made for beginners. Start building real JavaScript projects in under an hour."
  api: "https://gomakethings.com/api/data.json"
  sales: "https://gomakethings.com/checkout/wp-json/gmt-edd/v1/sales?category=guides&start=08-01-2016&round=10&96gdGDPqokbFsy3Lbx7LwTBdYNDxpo4a=GbwzXPHRqqCDKyy38TYmAybvV8AZZUJHmuA8zKKMjJ2ZUXFG7LcCy2rLAMmU8HEZ"
  font: "https://fonts.googleapis.com/css?family=PT+Serif:400,400i,700,700i&display=swap"
  rssURL: "https://gomakethings.com/feed/index.xml"
  rssLimit: 7
  studentURL: "https://courses.gomakethings.com"
  minify: true

# Caches
caches:
  getjson:
    maxAge: "10m"

# The language code for the site
languageCode: "en-us"

# Site title
title: "Vanilla JS Guides"

# theme to use (located by default in /themes/THEMENAME/)
theme: "guides"

# Permalinks
# See "content-management/permalinks"
permalinks:
  articles: /:title/

# Use absolute URLs
canonifyURLs: true

# Allows you to disable all page types and will render nothing related to 'kind';
# values = "page", "home", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"
disableKinds: ["RSS", "hugoGeneratorInject", "404"]

# Files to ignore while rendering
ignoreFiles: []

# the length of text to show in a .Summary
summaryLength: 70

# Pagination
paginate: 35
paginatePath: "page"

# Markdown Options
blackfriday:
  fractions: false

# Syntax Highlighting
pygmentsCodefences: true
pygmentsUseClasses: true